version: "2"
services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    container_name: shadowsocks
    environment:
      - PASSWORD=KJXutW4cUj
    ports:
      - 18548:8388
      - 18548:8388/udp
    restart: unless-stopped

  kcptun:
    image: xtaci/kcptun
    container_name: kcptun
    volumes:
      - ./kcptun_server.json:/etc/kcptun_server.json
    ports:
      - 29900:29900/udp
    command: server -c /etc/kcptun_server.json
    restart: unless-stopped
networks:
  default:
    external:
      name: shadowsocks